spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      host: mongodb
      port: 27017
      username: dictuser
      password: test
      database: dictionary
  elasticsearch:
    uris: http://elasticsearch:9200

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: debug