spring:
  kafka:
    bootstrap-servers: kafka:9092
  elasticsearch:
    uris: http://elasticsearch:9200
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: neo4jTtk-

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: DEBUG