spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      username: dictuser
      password: test
      database: dictionary
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: debug